package me.isaiah.common;

import java.util.Collection;
import java.util.Random;
import net.minecraft.world.Container;
import net.minecraft.world.item.ItemStack;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

/**
 */
public interface LootTable {

    /**
     * Returns a mutable list of loot generated by this LootTable.
     */
    @NotNull
    Collection<ItemStack> populateLoot(@Nullable Random random, @NotNull LootInfo context);

    /**
     * Attempt to fill an inventory with this LootTable's loot.
     */
    void fillInventory(@NotNull Container inventory, @Nullable Random random, @NotNull LootInfo context);

    /**
     */
    String get_key();

}
